//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-32267302
// Cuda compilation tools, release 12.0, V12.0.140
// Based on NVVM 7.0.1
//

.version 8.0
.target sm_52
.address_size 64

	// .globl	eigenBatchKernel
.extern .func  (.param .b32 func_retval0) vprintf
(
	.param .b64 vprintf_param_0,
	.param .b64 vprintf_param_1
)
;
.func  (.param .b64 func_retval0) __internal_trig_reduction_slowpathd
(
	.param .b64 __internal_trig_reduction_slowpathd_param_0,
	.param .b64 __internal_trig_reduction_slowpathd_param_1
)
;
.global .align 1 .b8 $str[87] = {118, 101, 99, 32, 105, 110, 32, 101, 105, 103, 101, 110, 86, 101, 99, 66, 97, 116, 99, 104, 51, 120, 51, 32, 119, 105, 116, 104, 32, 105, 110, 100, 101, 120, 32, 37, 100, 32, 45, 62, 32, 40, 37, 100, 44, 32, 37, 100, 41, 32, 105, 115, 32, 58, 32, 40, 37, 102, 46, 32, 37, 102, 44, 32, 37, 102, 41, 10, 119, 105, 116, 104, 32, 116, 111, 108, 101, 114, 97, 110, 99, 101, 32, 37, 102, 10, 0};
.global .align 1 .b8 $str$1[37] = {10, 77, 97, 116, 114, 105, 120, 58, 10, 37, 102, 32, 37, 102, 32, 37, 102, 10, 37, 102, 32, 37, 102, 32, 37, 102, 10, 37, 102, 32, 37, 102, 32, 37, 102, 10, 0};
.global .align 8 .b8 __cudart_sin_cos_coeffs[128] = {186, 94, 120, 249, 101, 219, 229, 61, 70, 210, 176, 44, 241, 229, 90, 190, 146, 227, 172, 105, 227, 29, 199, 62, 161, 98, 219, 25, 160, 1, 42, 191, 24, 8, 17, 17, 17, 17, 129, 63, 84, 85, 85, 85, 85, 85, 197, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 129, 253, 32, 131, 255, 168, 189, 40, 133, 239, 193, 167, 238, 33, 62, 217, 230, 6, 142, 79, 126, 146, 190, 233, 188, 221, 25, 160, 1, 250, 62, 71, 93, 193, 22, 108, 193, 86, 191, 81, 85, 85, 85, 85, 85, 165, 63, 0, 0, 0, 0, 0, 0, 224, 191, 0, 0, 0, 0, 0, 0, 240, 63};
.global .align 8 .b8 __cudart_i2opi_d[144] = {8, 93, 141, 31, 177, 95, 251, 107, 234, 146, 82, 138, 247, 57, 7, 61, 123, 241, 229, 235, 199, 186, 39, 117, 45, 234, 95, 158, 102, 63, 70, 79, 183, 9, 203, 39, 207, 126, 54, 109, 31, 109, 10, 90, 139, 17, 47, 239, 15, 152, 5, 222, 255, 151, 248, 31, 59, 40, 249, 189, 139, 95, 132, 156, 244, 57, 83, 131, 57, 214, 145, 57, 65, 126, 95, 180, 38, 112, 156, 233, 132, 68, 187, 46, 245, 53, 130, 232, 62, 167, 41, 177, 28, 235, 29, 254, 28, 146, 209, 9, 234, 46, 73, 6, 224, 210, 77, 66, 58, 110, 36, 183, 97, 197, 187, 222, 171, 99, 81, 254, 65, 144, 67, 60, 153, 149, 98, 219, 192, 221, 52, 245, 209, 87, 39, 252, 41, 21, 68, 78, 110, 131, 249, 162};

.visible .entry eigenBatchKernel(
	.param .u32 eigenBatchKernel_param_0,
	.param .u64 eigenBatchKernel_param_1,
	.param .u32 eigenBatchKernel_param_2,
	.param .u64 eigenBatchKernel_param_3,
	.param .u32 eigenBatchKernel_param_4,
	.param .u64 eigenBatchKernel_param_5,
	.param .u32 eigenBatchKernel_param_6,
	.param .u64 eigenBatchKernel_param_7,
	.param .u32 eigenBatchKernel_param_8,
	.param .u64 eigenBatchKernel_param_9,
	.param .u32 eigenBatchKernel_param_10,
	.param .u64 eigenBatchKernel_param_11,
	.param .u32 eigenBatchKernel_param_12,
	.param .u32 eigenBatchKernel_param_13,
	.param .u64 eigenBatchKernel_param_14,
	.param .u32 eigenBatchKernel_param_15,
	.param .u32 eigenBatchKernel_param_16,
	.param .u32 eigenBatchKernel_param_17,
	.param .u32 eigenBatchKernel_param_18,
	.param .u64 eigenBatchKernel_param_19,
	.param .u32 eigenBatchKernel_param_20,
	.param .u32 eigenBatchKernel_param_21,
	.param .f32 eigenBatchKernel_param_22
)
{
	.local .align 16 .b8 	__local_depot0[208];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<88>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<31>;
	.reg .b32 	%r<189>;
	.reg .f64 	%fd<700>;
	.reg .b64 	%rd<101>;


	mov.u64 	%SPL, __local_depot0;
	cvta.local.u64 	%SP, %SPL;
	ld.param.u32 	%r50, [eigenBatchKernel_param_0];
	ld.param.u64 	%rd14, [eigenBatchKernel_param_1];
	ld.param.u32 	%r38, [eigenBatchKernel_param_2];
	ld.param.u64 	%rd15, [eigenBatchKernel_param_3];
	ld.param.u32 	%r39, [eigenBatchKernel_param_4];
	ld.param.u64 	%rd16, [eigenBatchKernel_param_5];
	ld.param.u32 	%r40, [eigenBatchKernel_param_6];
	ld.param.u64 	%rd17, [eigenBatchKernel_param_7];
	ld.param.u32 	%r41, [eigenBatchKernel_param_8];
	ld.param.u64 	%rd18, [eigenBatchKernel_param_9];
	ld.param.u32 	%r42, [eigenBatchKernel_param_10];
	ld.param.u64 	%rd19, [eigenBatchKernel_param_11];
	ld.param.u32 	%r43, [eigenBatchKernel_param_12];
	ld.param.u32 	%r44, [eigenBatchKernel_param_13];
	ld.param.u64 	%rd20, [eigenBatchKernel_param_14];
	ld.param.u32 	%r45, [eigenBatchKernel_param_15];
	ld.param.u32 	%r46, [eigenBatchKernel_param_17];
	ld.param.u32 	%r49, [eigenBatchKernel_param_21];
	ld.param.f32 	%f5, [eigenBatchKernel_param_22];
	add.u64 	%rd2, %SPL, 8;
	add.u64 	%rd3, %SPL, 80;
	mov.u32 	%r51, %ntid.x;
	mov.u32 	%r52, %ctaid.x;
	mov.u32 	%r53, %tid.x;
	mad.lo.s32 	%r1, %r52, %r51, %r53;
	div.s32 	%r54, %r50, %r46;
	div.s32 	%r55, %r54, %r46;
	setp.ge.s32 	%p3, %r1, %r55;
	@%p3 bra 	$L__BB0_125;

	cvta.to.global.u64 	%rd25, %rd14;
	mul.lo.s32 	%r56, %r1, %r46;
	div.s32 	%r57, %r56, %r44;
	mul.lo.s32 	%r58, %r57, %r46;
	mul.lo.s32 	%r59, %r57, %r44;
	sub.s32 	%r60, %r56, %r59;
	mad.lo.s32 	%r61, %r58, %r38, %r60;
	mul.wide.s32 	%rd26, %r61, 4;
	add.s64 	%rd27, %rd25, %rd26;
	ld.global.f32 	%f6, [%rd27];
	mad.lo.s32 	%r62, %r58, %r39, %r60;
	cvta.to.global.u64 	%rd28, %rd15;
	mul.wide.s32 	%rd29, %r62, 4;
	add.s64 	%rd30, %rd28, %rd29;
	ld.global.f32 	%f7, [%rd30];
	mad.lo.s32 	%r63, %r58, %r40, %r60;
	cvta.to.global.u64 	%rd31, %rd16;
	mul.wide.s32 	%rd32, %r63, 4;
	add.s64 	%rd33, %rd31, %rd32;
	ld.global.f32 	%f8, [%rd33];
	mad.lo.s32 	%r64, %r58, %r41, %r60;
	cvta.to.global.u64 	%rd34, %rd17;
	mul.wide.s32 	%rd35, %r64, 4;
	add.s64 	%rd36, %rd34, %rd35;
	ld.global.f32 	%f9, [%rd36];
	mad.lo.s32 	%r65, %r58, %r42, %r60;
	cvta.to.global.u64 	%rd37, %rd18;
	mul.wide.s32 	%rd38, %r65, 4;
	add.s64 	%rd39, %rd37, %rd38;
	ld.global.f32 	%f10, [%rd39];
	mad.lo.s32 	%r66, %r58, %r43, %r60;
	cvta.to.global.u64 	%rd40, %rd19;
	mul.wide.s32 	%rd41, %r66, 4;
	add.s64 	%rd42, %rd40, %rd41;
	ld.global.f32 	%f11, [%rd42];
	add.s64 	%rd4, %rd3, 72;
	cvt.f64.f32 	%fd1, %f5;
	st.local.f64 	[%rd3+72], %fd1;
	cvt.f64.f32 	%fd2, %f6;
	st.local.f64 	[%rd3], %fd2;
	cvt.f64.f32 	%fd692, %f7;
	st.local.f64 	[%rd3+24], %fd692;
	st.local.f64 	[%rd3+8], %fd692;
	cvt.f64.f32 	%fd690, %f8;
	st.local.f64 	[%rd3+48], %fd690;
	st.local.f64 	[%rd3+16], %fd690;
	cvt.f64.f32 	%fd5, %f9;
	st.local.f64 	[%rd3+32], %fd5;
	cvt.f64.f32 	%fd681, %f10;
	st.local.f64 	[%rd3+56], %fd681;
	st.local.f64 	[%rd3+40], %fd681;
	cvt.f64.f32 	%fd7, %f11;
	st.local.f64 	[%rd3+64], %fd7;
	add.f64 	%fd160, %fd2, %fd5;
	add.f64 	%fd8, %fd160, %fd7;
	mul.f64 	%fd161, %fd5, %fd7;
	mul.f64 	%fd162, %fd681, %fd681;
	sub.f64 	%fd163, %fd161, %fd162;
	fma.rn.f64 	%fd164, %fd2, %fd7, %fd163;
	mul.f64 	%fd165, %fd690, %fd690;
	sub.f64 	%fd166, %fd164, %fd165;
	fma.rn.f64 	%fd167, %fd2, %fd5, %fd166;
	mul.f64 	%fd168, %fd692, %fd692;
	sub.f64 	%fd169, %fd167, %fd168;
	mul.f64 	%fd170, %fd163, %fd2;
	mul.f64 	%fd171, %fd692, %fd7;
	mul.f64 	%fd172, %fd681, %fd690;
	sub.f64 	%fd173, %fd171, %fd172;
	mul.f64 	%fd174, %fd173, %fd692;
	sub.f64 	%fd175, %fd170, %fd174;
	mul.f64 	%fd176, %fd692, %fd681;
	mul.f64 	%fd177, %fd5, %fd690;
	sub.f64 	%fd178, %fd176, %fd177;
	fma.rn.f64 	%fd179, %fd178, %fd690, %fd175;
	mul.lo.s32 	%r67, %r1, 3;
	div.s32 	%r2, %r67, %r49;
	mul.lo.s32 	%r68, %r2, %r49;
	sub.s32 	%r3, %r67, %r68;
	mad.lo.s32 	%r69, %r2, %r45, %r3;
	mul.f64 	%fd180, %fd8, %fd8;
	div.rn.f64 	%fd181, %fd169, 0d4008000000000000;
	div.rn.f64 	%fd182, %fd180, 0dC022000000000000;
	add.f64 	%fd9, %fd181, %fd182;
	mul.f64 	%fd183, %fd180, %fd8;
	div.rn.f64 	%fd184, %fd183, 0dC02B000000000000;
	mul.f64 	%fd185, %fd169, %fd8;
	div.rn.f64 	%fd186, %fd185, 0d4008000000000000;
	add.f64 	%fd187, %fd186, %fd184;
	sub.f64 	%fd10, %fd187, %fd179;
	setp.ltu.f64 	%p4, %fd9, 0dBE112E0BE826D695;
	cvta.to.global.u64 	%rd43, %rd20;
	mul.wide.s32 	%rd44, %r69, 4;
	add.s64 	%rd5, %rd43, %rd44;
	@%p4 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	neg.f64 	%fd188, %fd9;
	sqrt.rn.f64 	%fd189, %fd188;
	add.f64 	%fd12, %fd189, %fd189;
	div.rn.f64 	%fd13, %fd8, 0d4008000000000000;
	mul.f64 	%fd190, %fd9, %fd12;
	div.rn.f64 	%fd14, %fd10, %fd190;
	setp.gt.f64 	%p5, %fd14, 0d3FEFFFFDE7210BE9;
	@%p5 bra 	$L__BB0_67;
	bra.uni 	$L__BB0_4;

$L__BB0_67:
	add.f64 	%fd672, %fd13, %fd12;
	st.local.f64 	[%rd2], %fd672;
	fma.rn.f64 	%fd670, %fd12, 0dBFE0000000000000, %fd13;
	st.local.f64 	[%rd2+16], %fd670;
	st.local.f64 	[%rd2+8], %fd670;
	mov.f64 	%fd671, %fd670;
	bra.uni 	$L__BB0_68;

$L__BB0_2:
	div.rn.f64 	%fd679, %fd8, 0d4008000000000000;
	cvt.rn.f32.f64 	%f12, %fd679;
	st.global.f32 	[%rd5], %f12;
	st.global.f32 	[%rd5+4], %f12;
	st.global.f32 	[%rd5+8], %f12;
	bra.uni 	$L__BB0_75;

$L__BB0_4:
	setp.lt.f64 	%p6, %fd14, 0dBFEFFFFDE7210BE9;
	@%p6 bra 	$L__BB0_66;
	bra.uni 	$L__BB0_5;

$L__BB0_66:
	sub.f64 	%fd672, %fd13, %fd12;
	st.local.f64 	[%rd2], %fd672;
	fma.rn.f64 	%fd670, %fd12, 0d3FE0000000000000, %fd13;
	st.local.f64 	[%rd2+16], %fd670;
	st.local.f64 	[%rd2+8], %fd670;
	mov.f64 	%fd671, %fd670;
	bra.uni 	$L__BB0_68;

$L__BB0_5:
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r4}, %fd14;
	}
	abs.f64 	%fd15, %fd14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r5}, %fd15;
	}
	setp.lt.s32 	%p7, %r5, 1071801958;
	mul.f64 	%fd16, %fd15, %fd15;
	mov.f64 	%fd191, 0d3FF0000000000000;
	sub.f64 	%fd17, %fd191, %fd15;
	@%p7 bra 	$L__BB0_13;
	bra.uni 	$L__BB0_6;

$L__BB0_13:
	setp.lt.s32 	%p11, %r4, 0;
	mov.f64 	%fd238, 0dBFB3823B180754AF;
	mov.f64 	%fd239, 0d3FB0066BDC1895E9;
	fma.rn.f64 	%fd240, %fd239, %fd16, %fd238;
	mov.f64 	%fd241, 0d3FB11E52CC2F79AE;
	fma.rn.f64 	%fd242, %fd240, %fd16, %fd241;
	mov.f64 	%fd243, 0dBF924EAF3526861B;
	fma.rn.f64 	%fd244, %fd242, %fd16, %fd243;
	mov.f64 	%fd245, 0d3F91DF02A31E6CB7;
	fma.rn.f64 	%fd246, %fd244, %fd16, %fd245;
	mov.f64 	%fd247, 0d3F847D18B0EEC6CC;
	fma.rn.f64 	%fd248, %fd246, %fd16, %fd247;
	mov.f64 	%fd249, 0d3F8D0AF961BA53B0;
	fma.rn.f64 	%fd250, %fd248, %fd16, %fd249;
	mov.f64 	%fd251, 0d3F91BF7734CF1C48;
	fma.rn.f64 	%fd252, %fd250, %fd16, %fd251;
	mov.f64 	%fd253, 0d3F96E91483144EF7;
	fma.rn.f64 	%fd254, %fd252, %fd16, %fd253;
	mov.f64 	%fd255, 0d3F9F1C6E0A4F9F81;
	fma.rn.f64 	%fd256, %fd254, %fd16, %fd255;
	mov.f64 	%fd257, 0d3FA6DB6DC27FA92B;
	fma.rn.f64 	%fd258, %fd256, %fd16, %fd257;
	mov.f64 	%fd259, 0d3FB333333320F91B;
	fma.rn.f64 	%fd260, %fd258, %fd16, %fd259;
	mov.f64 	%fd261, 0d3FC5555555555F4D;
	fma.rn.f64 	%fd262, %fd260, %fd16, %fd261;
	mul.f64 	%fd263, %fd16, %fd262;
	fma.rn.f64 	%fd24, %fd263, %fd15, %fd15;
	@%p11 bra 	$L__BB0_15;

	mov.f64 	%fd264, 0dBC91A62633145C07;
	add.rn.f64 	%fd265, %fd24, %fd264;
	neg.f64 	%fd266, %fd265;
	mov.f64 	%fd267, 0d3FF921FB54442D18;
	add.rn.f64 	%fd651, %fd267, %fd266;
	bra.uni 	$L__BB0_16;

$L__BB0_6:
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r6}, %fd17;
	}
	setp.lt.s32 	%p8, %r6, 1;
	@%p8 bra 	$L__BB0_8;

	add.s32 	%r70, %r6, -1048576;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r71, %temp}, %fd17;
	}
	mov.b64 	%fd192, {%r71, %r70};
	rsqrt.approx.ftz.f64 	%fd193, %fd192;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r72}, %fd193;
	}
	add.s32 	%r73, %r72, -1048576;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r74, %temp}, %fd193;
	}
	mov.b64 	%fd194, {%r74, %r73};
	mul.f64 	%fd195, %fd192, %fd193;
	neg.f64 	%fd196, %fd195;
	fma.rn.f64 	%fd197, %fd195, %fd196, %fd192;
	fma.rn.f64 	%fd198, %fd197, %fd194, %fd195;
	neg.f64 	%fd199, %fd198;
	fma.rn.f64 	%fd200, %fd198, %fd199, %fd192;
	mov.f64 	%fd201, 0d3FF0000000000000;
	fma.rn.f64 	%fd202, %fd193, %fd199, %fd201;
	fma.rn.f64 	%fd203, %fd202, %fd194, %fd194;
	fma.rn.f64 	%fd204, %fd200, %fd203, %fd198;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r75}, %fd204;
	}
	add.s32 	%r76, %r75, 1048576;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r77, %temp}, %fd204;
	}
	mov.b64 	%fd205, {%r77, %r76};
	mov.f64 	%fd206, 0dBEBAC2FE66FAAC4B;
	mov.f64 	%fd207, 0d3EC715B371155F70;
	fma.rn.f64 	%fd208, %fd207, %fd17, %fd206;
	mov.f64 	%fd209, 0d3ED9A9B88EFCD9B8;
	fma.rn.f64 	%fd210, %fd208, %fd17, %fd209;
	mov.f64 	%fd211, 0d3EDD0F40A8A0C4C3;
	fma.rn.f64 	%fd212, %fd210, %fd17, %fd211;
	mov.f64 	%fd213, 0d3EF46D4CFA9E0E1F;
	fma.rn.f64 	%fd214, %fd212, %fd17, %fd213;
	mov.f64 	%fd215, 0d3F079C168D1E2422;
	fma.rn.f64 	%fd216, %fd214, %fd17, %fd215;
	mov.f64 	%fd217, 0d3F1C9A88C3BCA540;
	fma.rn.f64 	%fd218, %fd216, %fd17, %fd217;
	mov.f64 	%fd219, 0d3F31C4E64BD476DF;
	fma.rn.f64 	%fd220, %fd218, %fd17, %fd219;
	mov.f64 	%fd221, 0d3F46E8BA60009C8F;
	fma.rn.f64 	%fd222, %fd220, %fd17, %fd221;
	mov.f64 	%fd223, 0d3F5F1C71C62B05A2;
	fma.rn.f64 	%fd224, %fd222, %fd17, %fd223;
	mov.f64 	%fd225, 0d3F76DB6DB6DC9F2C;
	fma.rn.f64 	%fd226, %fd224, %fd17, %fd225;
	mov.f64 	%fd227, 0d3F9333333333329C;
	fma.rn.f64 	%fd228, %fd226, %fd17, %fd227;
	mov.f64 	%fd229, 0d3FB5555555555555;
	fma.rn.f64 	%fd230, %fd228, %fd17, %fd229;
	mul.f64 	%fd231, %fd17, %fd230;
	fma.rn.f64 	%fd651, %fd231, %fd205, %fd205;
	bra.uni 	$L__BB0_9;

$L__BB0_15:
	mov.f64 	%fd268, 0d3C91A62633145C07;
	add.rn.f64 	%fd269, %fd24, %fd268;
	mov.f64 	%fd270, 0d3FF921FB54442D18;
	add.rn.f64 	%fd651, %fd270, %fd269;
	bra.uni 	$L__BB0_16;

$L__BB0_8:
	mov.f64 	%fd232, 0d0000000000000000;
	mul.rn.f64 	%fd651, %fd15, %fd232;

$L__BB0_9:
	abs.f64 	%fd625, %fd14;
	mov.f64 	%fd624, 0d3FF0000000000000;
	sub.f64 	%fd623, %fd624, %fd625;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r162}, %fd623;
	}
	setp.gt.s32 	%p9, %r162, -1;
	@%p9 bra 	$L__BB0_11;

	mov.f64 	%fd233, 0d7FF0000000000000;
	mul.rn.f64 	%fd651, %fd651, %fd233;

$L__BB0_11:
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r163}, %fd14;
	}
	setp.gt.s32 	%p10, %r163, -1;
	@%p10 bra 	$L__BB0_16;

	mov.f64 	%fd234, 0dBCA1A62633145C07;
	add.rn.f64 	%fd235, %fd651, %fd234;
	neg.f64 	%fd236, %fd235;
	mov.f64 	%fd237, 0d400921FB54442D18;
	add.rn.f64 	%fd651, %fd237, %fd236;

$L__BB0_16:
	add.f64 	%fd271, %fd651, 0d0000000000000000;
	div.rn.f64 	%fd28, %fd271, 0d4008000000000000;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r78, %temp}, %fd28;
	}
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r79}, %fd28;
	}
	and.b32  	%r80, %r79, 2147483647;
	setp.eq.s32 	%p12, %r80, 2146435072;
	setp.eq.s32 	%p13, %r78, 0;
	and.pred  	%p14, %p13, %p12;
	@%p14 bra 	$L__BB0_20;
	bra.uni 	$L__BB0_17;

$L__BB0_20:
	mov.f64 	%fd281, 0d0000000000000000;
	mul.rn.f64 	%fd653, %fd28, %fd281;
	mov.u32 	%r181, 1;
	bra.uni 	$L__BB0_21;

$L__BB0_17:
	add.u64 	%rd97, %SPL, 0;
	mul.f64 	%fd272, %fd28, 0d3FE45F306DC9C883;
	cvt.rni.s32.f64 	%r180, %fd272;
	st.local.u32 	[%rd97], %r180;
	cvt.rn.f64.s32 	%fd273, %r180;
	neg.f64 	%fd274, %fd273;
	mov.f64 	%fd275, 0d3FF921FB54442D18;
	fma.rn.f64 	%fd276, %fd274, %fd275, %fd28;
	mov.f64 	%fd277, 0d3C91A62633145C00;
	fma.rn.f64 	%fd278, %fd274, %fd277, %fd276;
	mov.f64 	%fd279, 0d397B839A252049C0;
	fma.rn.f64 	%fd653, %fd274, %fd279, %fd278;
	abs.f64 	%fd280, %fd28;
	setp.ltu.f64 	%p15, %fd280, 0d41E0000000000000;
	@%p15 bra 	$L__BB0_19;

	add.u64 	%rd99, %SPL, 0;
	add.u64 	%rd82, %SP, 0;
	{ // callseq 0, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.f64 	[param0+0], %fd28;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd82;
	.param .b64 retval0;
	call.uni (retval0), 
	__internal_trig_reduction_slowpathd, 
	(
	param0, 
	param1
	);
	ld.param.f64 	%fd653, [retval0+0];
	} // callseq 0
	ld.local.u32 	%r180, [%rd99];

$L__BB0_19:
	add.s32 	%r181, %r180, 1;

$L__BB0_21:
	and.b32  	%r82, %r181, 1;
	shl.b32 	%r83, %r181, 3;
	and.b32  	%r84, %r83, 8;
	setp.eq.s32 	%p16, %r82, 0;
	selp.f64 	%fd282, 0d3DE5DB65F9785EBA, 0dBDA8FF8320FD8164, %p16;
	mul.wide.s32 	%rd46, %r84, 8;
	mov.u64 	%rd47, __cudart_sin_cos_coeffs;
	add.s64 	%rd48, %rd47, %rd46;
	ld.global.nc.f64 	%fd283, [%rd48+8];
	mul.rn.f64 	%fd34, %fd653, %fd653;
	fma.rn.f64 	%fd284, %fd282, %fd34, %fd283;
	ld.global.nc.f64 	%fd285, [%rd48+16];
	fma.rn.f64 	%fd286, %fd284, %fd34, %fd285;
	ld.global.nc.f64 	%fd287, [%rd48+24];
	fma.rn.f64 	%fd288, %fd286, %fd34, %fd287;
	ld.global.nc.f64 	%fd289, [%rd48+32];
	fma.rn.f64 	%fd290, %fd288, %fd34, %fd289;
	ld.global.nc.f64 	%fd291, [%rd48+40];
	fma.rn.f64 	%fd292, %fd290, %fd34, %fd291;
	ld.global.nc.f64 	%fd293, [%rd48+48];
	fma.rn.f64 	%fd35, %fd292, %fd34, %fd293;
	fma.rn.f64 	%fd655, %fd35, %fd653, %fd653;
	@%p16 bra 	$L__BB0_23;

	mov.f64 	%fd294, 0d3FF0000000000000;
	fma.rn.f64 	%fd655, %fd35, %fd34, %fd294;

$L__BB0_23:
	and.b32  	%r85, %r181, 2;
	setp.eq.s32 	%p17, %r85, 0;
	@%p17 bra 	$L__BB0_25;

	mov.f64 	%fd295, 0d0000000000000000;
	mov.f64 	%fd296, 0dBFF0000000000000;
	fma.rn.f64 	%fd655, %fd655, %fd296, %fd295;

$L__BB0_25:
	abs.f64 	%fd642, %fd14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r179}, %fd642;
	}
	setp.lt.s32 	%p85, %r179, 1071801958;
	fma.rn.f64 	%fd672, %fd12, %fd655, %fd13;
	st.local.f64 	[%rd2], %fd672;
	@%p85 bra 	$L__BB0_33;
	bra.uni 	$L__BB0_26;

$L__BB0_33:
	abs.f64 	%fd631, %fd14;
	mul.f64 	%fd630, %fd631, %fd631;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r176}, %fd14;
	}
	setp.lt.s32 	%p22, %r176, 0;
	mov.f64 	%fd343, 0dBFB3823B180754AF;
	mov.f64 	%fd344, 0d3FB0066BDC1895E9;
	fma.rn.f64 	%fd345, %fd344, %fd630, %fd343;
	mov.f64 	%fd346, 0d3FB11E52CC2F79AE;
	fma.rn.f64 	%fd347, %fd345, %fd630, %fd346;
	mov.f64 	%fd348, 0dBF924EAF3526861B;
	fma.rn.f64 	%fd349, %fd347, %fd630, %fd348;
	mov.f64 	%fd350, 0d3F91DF02A31E6CB7;
	fma.rn.f64 	%fd351, %fd349, %fd630, %fd350;
	mov.f64 	%fd352, 0d3F847D18B0EEC6CC;
	fma.rn.f64 	%fd353, %fd351, %fd630, %fd352;
	mov.f64 	%fd354, 0d3F8D0AF961BA53B0;
	fma.rn.f64 	%fd355, %fd353, %fd630, %fd354;
	mov.f64 	%fd356, 0d3F91BF7734CF1C48;
	fma.rn.f64 	%fd357, %fd355, %fd630, %fd356;
	mov.f64 	%fd358, 0d3F96E91483144EF7;
	fma.rn.f64 	%fd359, %fd357, %fd630, %fd358;
	mov.f64 	%fd360, 0d3F9F1C6E0A4F9F81;
	fma.rn.f64 	%fd361, %fd359, %fd630, %fd360;
	mov.f64 	%fd362, 0d3FA6DB6DC27FA92B;
	fma.rn.f64 	%fd363, %fd361, %fd630, %fd362;
	mov.f64 	%fd364, 0d3FB333333320F91B;
	fma.rn.f64 	%fd365, %fd363, %fd630, %fd364;
	mov.f64 	%fd366, 0d3FC5555555555F4D;
	fma.rn.f64 	%fd367, %fd365, %fd630, %fd366;
	mul.f64 	%fd368, %fd630, %fd367;
	fma.rn.f64 	%fd48, %fd368, %fd631, %fd631;
	@%p22 bra 	$L__BB0_35;

	mov.f64 	%fd369, 0dBC91A62633145C07;
	add.rn.f64 	%fd370, %fd48, %fd369;
	neg.f64 	%fd371, %fd370;
	mov.f64 	%fd372, 0d3FF921FB54442D18;
	add.rn.f64 	%fd658, %fd372, %fd371;
	bra.uni 	$L__BB0_36;

$L__BB0_26:
	abs.f64 	%fd645, %fd14;
	mov.f64 	%fd644, 0d3FF0000000000000;
	sub.f64 	%fd643, %fd644, %fd645;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r12}, %fd643;
	}
	setp.lt.s32 	%p19, %r12, 1;
	@%p19 bra 	$L__BB0_28;

	abs.f64 	%fd648, %fd14;
	mov.f64 	%fd647, 0d3FF0000000000000;
	sub.f64 	%fd646, %fd647, %fd648;
	add.s32 	%r86, %r12, -1048576;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r87, %temp}, %fd646;
	}
	mov.b64 	%fd297, {%r87, %r86};
	rsqrt.approx.ftz.f64 	%fd298, %fd297;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r88}, %fd298;
	}
	add.s32 	%r89, %r88, -1048576;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r90, %temp}, %fd298;
	}
	mov.b64 	%fd299, {%r90, %r89};
	mul.f64 	%fd300, %fd297, %fd298;
	neg.f64 	%fd301, %fd300;
	fma.rn.f64 	%fd302, %fd300, %fd301, %fd297;
	fma.rn.f64 	%fd303, %fd302, %fd299, %fd300;
	neg.f64 	%fd304, %fd303;
	fma.rn.f64 	%fd305, %fd303, %fd304, %fd297;
	mov.f64 	%fd306, 0d3FF0000000000000;
	fma.rn.f64 	%fd307, %fd298, %fd304, %fd306;
	fma.rn.f64 	%fd308, %fd307, %fd299, %fd299;
	fma.rn.f64 	%fd309, %fd305, %fd308, %fd303;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r91}, %fd309;
	}
	add.s32 	%r92, %r91, 1048576;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r93, %temp}, %fd309;
	}
	mov.b64 	%fd310, {%r93, %r92};
	mov.f64 	%fd311, 0dBEBAC2FE66FAAC4B;
	mov.f64 	%fd312, 0d3EC715B371155F70;
	fma.rn.f64 	%fd313, %fd312, %fd646, %fd311;
	mov.f64 	%fd314, 0d3ED9A9B88EFCD9B8;
	fma.rn.f64 	%fd315, %fd313, %fd646, %fd314;
	mov.f64 	%fd316, 0d3EDD0F40A8A0C4C3;
	fma.rn.f64 	%fd317, %fd315, %fd646, %fd316;
	mov.f64 	%fd318, 0d3EF46D4CFA9E0E1F;
	fma.rn.f64 	%fd319, %fd317, %fd646, %fd318;
	mov.f64 	%fd320, 0d3F079C168D1E2422;
	fma.rn.f64 	%fd321, %fd319, %fd646, %fd320;
	mov.f64 	%fd322, 0d3F1C9A88C3BCA540;
	fma.rn.f64 	%fd323, %fd321, %fd646, %fd322;
	mov.f64 	%fd324, 0d3F31C4E64BD476DF;
	fma.rn.f64 	%fd325, %fd323, %fd646, %fd324;
	mov.f64 	%fd326, 0d3F46E8BA60009C8F;
	fma.rn.f64 	%fd327, %fd325, %fd646, %fd326;
	mov.f64 	%fd328, 0d3F5F1C71C62B05A2;
	fma.rn.f64 	%fd329, %fd327, %fd646, %fd328;
	mov.f64 	%fd330, 0d3F76DB6DB6DC9F2C;
	fma.rn.f64 	%fd331, %fd329, %fd646, %fd330;
	mov.f64 	%fd332, 0d3F9333333333329C;
	fma.rn.f64 	%fd333, %fd331, %fd646, %fd332;
	mov.f64 	%fd334, 0d3FB5555555555555;
	fma.rn.f64 	%fd335, %fd333, %fd646, %fd334;
	mul.f64 	%fd336, %fd646, %fd335;
	fma.rn.f64 	%fd658, %fd336, %fd310, %fd310;
	bra.uni 	$L__BB0_29;

$L__BB0_35:
	mov.f64 	%fd373, 0d3C91A62633145C07;
	add.rn.f64 	%fd374, %fd48, %fd373;
	mov.f64 	%fd375, 0d3FF921FB54442D18;
	add.rn.f64 	%fd658, %fd375, %fd374;
	bra.uni 	$L__BB0_36;

$L__BB0_28:
	abs.f64 	%fd629, %fd14;
	mov.f64 	%fd337, 0d0000000000000000;
	mul.rn.f64 	%fd658, %fd629, %fd337;

$L__BB0_29:
	abs.f64 	%fd634, %fd14;
	mov.f64 	%fd633, 0d3FF0000000000000;
	sub.f64 	%fd632, %fd633, %fd634;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r177}, %fd632;
	}
	setp.gt.s32 	%p20, %r177, -1;
	@%p20 bra 	$L__BB0_31;

	mov.f64 	%fd338, 0d7FF0000000000000;
	mul.rn.f64 	%fd658, %fd658, %fd338;

$L__BB0_31:
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r164}, %fd14;
	}
	setp.gt.s32 	%p21, %r164, -1;
	@%p21 bra 	$L__BB0_36;

	mov.f64 	%fd339, 0dBCA1A62633145C07;
	add.rn.f64 	%fd340, %fd658, %fd339;
	neg.f64 	%fd341, %fd340;
	mov.f64 	%fd342, 0d400921FB54442D18;
	add.rn.f64 	%fd658, %fd342, %fd341;

$L__BB0_36:
	add.f64 	%fd376, %fd658, 0d401921FB54442D18;
	div.rn.f64 	%fd52, %fd376, 0d4008000000000000;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r94, %temp}, %fd52;
	}
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r95}, %fd52;
	}
	and.b32  	%r96, %r95, 2147483647;
	setp.eq.s32 	%p23, %r96, 2146435072;
	setp.eq.s32 	%p24, %r94, 0;
	and.pred  	%p25, %p24, %p23;
	@%p25 bra 	$L__BB0_40;
	bra.uni 	$L__BB0_37;

$L__BB0_40:
	mov.f64 	%fd386, 0d0000000000000000;
	mul.rn.f64 	%fd660, %fd52, %fd386;
	mov.u32 	%r183, 1;
	bra.uni 	$L__BB0_41;

$L__BB0_37:
	add.u64 	%rd87, %SPL, 0;
	mul.f64 	%fd377, %fd52, 0d3FE45F306DC9C883;
	cvt.rni.s32.f64 	%r182, %fd377;
	st.local.u32 	[%rd87], %r182;
	cvt.rn.f64.s32 	%fd378, %r182;
	neg.f64 	%fd379, %fd378;
	mov.f64 	%fd380, 0d3FF921FB54442D18;
	fma.rn.f64 	%fd381, %fd379, %fd380, %fd52;
	mov.f64 	%fd382, 0d3C91A62633145C00;
	fma.rn.f64 	%fd383, %fd379, %fd382, %fd381;
	mov.f64 	%fd384, 0d397B839A252049C0;
	fma.rn.f64 	%fd660, %fd379, %fd384, %fd383;
	abs.f64 	%fd385, %fd52;
	setp.ltu.f64 	%p26, %fd385, 0d41E0000000000000;
	@%p26 bra 	$L__BB0_39;

	add.u64 	%rd89, %SPL, 0;
	add.u64 	%rd83, %SP, 0;
	{ // callseq 1, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.f64 	[param0+0], %fd52;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd83;
	.param .b64 retval0;
	call.uni (retval0), 
	__internal_trig_reduction_slowpathd, 
	(
	param0, 
	param1
	);
	ld.param.f64 	%fd660, [retval0+0];
	} // callseq 1
	ld.local.u32 	%r182, [%rd89];

$L__BB0_39:
	add.s32 	%r183, %r182, 1;

$L__BB0_41:
	mov.u64 	%rd91, __cudart_sin_cos_coeffs;
	and.b32  	%r98, %r183, 1;
	shl.b32 	%r99, %r183, 3;
	and.b32  	%r100, %r99, 8;
	setp.eq.s32 	%p27, %r98, 0;
	selp.f64 	%fd387, 0d3DE5DB65F9785EBA, 0dBDA8FF8320FD8164, %p27;
	mul.wide.s32 	%rd50, %r100, 8;
	add.s64 	%rd52, %rd91, %rd50;
	ld.global.nc.f64 	%fd388, [%rd52+8];
	mul.rn.f64 	%fd58, %fd660, %fd660;
	fma.rn.f64 	%fd389, %fd387, %fd58, %fd388;
	ld.global.nc.f64 	%fd390, [%rd52+16];
	fma.rn.f64 	%fd391, %fd389, %fd58, %fd390;
	ld.global.nc.f64 	%fd392, [%rd52+24];
	fma.rn.f64 	%fd393, %fd391, %fd58, %fd392;
	ld.global.nc.f64 	%fd394, [%rd52+32];
	fma.rn.f64 	%fd395, %fd393, %fd58, %fd394;
	ld.global.nc.f64 	%fd396, [%rd52+40];
	fma.rn.f64 	%fd397, %fd395, %fd58, %fd396;
	ld.global.nc.f64 	%fd398, [%rd52+48];
	fma.rn.f64 	%fd59, %fd397, %fd58, %fd398;
	fma.rn.f64 	%fd662, %fd59, %fd660, %fd660;
	@%p27 bra 	$L__BB0_43;

	mov.f64 	%fd399, 0d3FF0000000000000;
	fma.rn.f64 	%fd662, %fd59, %fd58, %fd399;

$L__BB0_43:
	and.b32  	%r101, %r183, 2;
	setp.eq.s32 	%p28, %r101, 0;
	@%p28 bra 	$L__BB0_45;

	mov.f64 	%fd400, 0d0000000000000000;
	mov.f64 	%fd401, 0dBFF0000000000000;
	fma.rn.f64 	%fd662, %fd662, %fd401, %fd400;

$L__BB0_45:
	abs.f64 	%fd635, %fd14;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r178}, %fd635;
	}
	setp.lt.s32 	%p84, %r178, 1071801958;
	fma.rn.f64 	%fd671, %fd12, %fd662, %fd13;
	st.local.f64 	[%rd2+8], %fd671;
	@%p84 bra 	$L__BB0_53;
	bra.uni 	$L__BB0_46;

$L__BB0_53:
	abs.f64 	%fd628, %fd14;
	mul.f64 	%fd627, %fd628, %fd628;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r175}, %fd14;
	}
	setp.lt.s32 	%p33, %r175, 0;
	mov.f64 	%fd448, 0dBFB3823B180754AF;
	mov.f64 	%fd449, 0d3FB0066BDC1895E9;
	fma.rn.f64 	%fd450, %fd449, %fd627, %fd448;
	mov.f64 	%fd451, 0d3FB11E52CC2F79AE;
	fma.rn.f64 	%fd452, %fd450, %fd627, %fd451;
	mov.f64 	%fd453, 0dBF924EAF3526861B;
	fma.rn.f64 	%fd454, %fd452, %fd627, %fd453;
	mov.f64 	%fd455, 0d3F91DF02A31E6CB7;
	fma.rn.f64 	%fd456, %fd454, %fd627, %fd455;
	mov.f64 	%fd457, 0d3F847D18B0EEC6CC;
	fma.rn.f64 	%fd458, %fd456, %fd627, %fd457;
	mov.f64 	%fd459, 0d3F8D0AF961BA53B0;
	fma.rn.f64 	%fd460, %fd458, %fd627, %fd459;
	mov.f64 	%fd461, 0d3F91BF7734CF1C48;
	fma.rn.f64 	%fd462, %fd460, %fd627, %fd461;
	mov.f64 	%fd463, 0d3F96E91483144EF7;
	fma.rn.f64 	%fd464, %fd462, %fd627, %fd463;
	mov.f64 	%fd465, 0d3F9F1C6E0A4F9F81;
	fma.rn.f64 	%fd466, %fd464, %fd627, %fd465;
	mov.f64 	%fd467, 0d3FA6DB6DC27FA92B;
	fma.rn.f64 	%fd468, %fd466, %fd627, %fd467;
	mov.f64 	%fd469, 0d3FB333333320F91B;
	fma.rn.f64 	%fd470, %fd468, %fd627, %fd469;
	mov.f64 	%fd471, 0d3FC5555555555F4D;
	fma.rn.f64 	%fd472, %fd470, %fd627, %fd471;
	mul.f64 	%fd473, %fd627, %fd472;
	fma.rn.f64 	%fd72, %fd473, %fd628, %fd628;
	@%p33 bra 	$L__BB0_55;

	mov.f64 	%fd474, 0dBC91A62633145C07;
	add.rn.f64 	%fd475, %fd72, %fd474;
	neg.f64 	%fd476, %fd475;
	mov.f64 	%fd477, 0d3FF921FB54442D18;
	add.rn.f64 	%fd665, %fd477, %fd476;
	bra.uni 	$L__BB0_56;

$L__BB0_46:
	abs.f64 	%fd638, %fd14;
	mov.f64 	%fd637, 0d3FF0000000000000;
	sub.f64 	%fd636, %fd637, %fd638;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r18}, %fd636;
	}
	setp.lt.s32 	%p30, %r18, 1;
	@%p30 bra 	$L__BB0_48;

	abs.f64 	%fd641, %fd14;
	mov.f64 	%fd640, 0d3FF0000000000000;
	sub.f64 	%fd639, %fd640, %fd641;
	add.s32 	%r102, %r18, -1048576;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r103, %temp}, %fd639;
	}
	mov.b64 	%fd402, {%r103, %r102};
	rsqrt.approx.ftz.f64 	%fd403, %fd402;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r104}, %fd403;
	}
	add.s32 	%r105, %r104, -1048576;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r106, %temp}, %fd403;
	}
	mov.b64 	%fd404, {%r106, %r105};
	mul.f64 	%fd405, %fd402, %fd403;
	neg.f64 	%fd406, %fd405;
	fma.rn.f64 	%fd407, %fd405, %fd406, %fd402;
	fma.rn.f64 	%fd408, %fd407, %fd404, %fd405;
	neg.f64 	%fd409, %fd408;
	fma.rn.f64 	%fd410, %fd408, %fd409, %fd402;
	mov.f64 	%fd411, 0d3FF0000000000000;
	fma.rn.f64 	%fd412, %fd403, %fd409, %fd411;
	fma.rn.f64 	%fd413, %fd412, %fd404, %fd404;
	fma.rn.f64 	%fd414, %fd410, %fd413, %fd408;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r107}, %fd414;
	}
	add.s32 	%r108, %r107, 1048576;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r109, %temp}, %fd414;
	}
	mov.b64 	%fd415, {%r109, %r108};
	mov.f64 	%fd416, 0dBEBAC2FE66FAAC4B;
	mov.f64 	%fd417, 0d3EC715B371155F70;
	fma.rn.f64 	%fd418, %fd417, %fd639, %fd416;
	mov.f64 	%fd419, 0d3ED9A9B88EFCD9B8;
	fma.rn.f64 	%fd420, %fd418, %fd639, %fd419;
	mov.f64 	%fd421, 0d3EDD0F40A8A0C4C3;
	fma.rn.f64 	%fd422, %fd420, %fd639, %fd421;
	mov.f64 	%fd423, 0d3EF46D4CFA9E0E1F;
	fma.rn.f64 	%fd424, %fd422, %fd639, %fd423;
	mov.f64 	%fd425, 0d3F079C168D1E2422;
	fma.rn.f64 	%fd426, %fd424, %fd639, %fd425;
	mov.f64 	%fd427, 0d3F1C9A88C3BCA540;
	fma.rn.f64 	%fd428, %fd426, %fd639, %fd427;
	mov.f64 	%fd429, 0d3F31C4E64BD476DF;
	fma.rn.f64 	%fd430, %fd428, %fd639, %fd429;
	mov.f64 	%fd431, 0d3F46E8BA60009C8F;
	fma.rn.f64 	%fd432, %fd430, %fd639, %fd431;
	mov.f64 	%fd433, 0d3F5F1C71C62B05A2;
	fma.rn.f64 	%fd434, %fd432, %fd639, %fd433;
	mov.f64 	%fd435, 0d3F76DB6DB6DC9F2C;
	fma.rn.f64 	%fd436, %fd434, %fd639, %fd435;
	mov.f64 	%fd437, 0d3F9333333333329C;
	fma.rn.f64 	%fd438, %fd436, %fd639, %fd437;
	mov.f64 	%fd439, 0d3FB5555555555555;
	fma.rn.f64 	%fd440, %fd438, %fd639, %fd439;
	mul.f64 	%fd441, %fd639, %fd440;
	fma.rn.f64 	%fd665, %fd441, %fd415, %fd415;
	bra.uni 	$L__BB0_49;

$L__BB0_55:
	mov.f64 	%fd478, 0d3C91A62633145C07;
	add.rn.f64 	%fd479, %fd72, %fd478;
	mov.f64 	%fd480, 0d3FF921FB54442D18;
	add.rn.f64 	%fd665, %fd480, %fd479;
	bra.uni 	$L__BB0_56;

$L__BB0_48:
	abs.f64 	%fd626, %fd14;
	mov.f64 	%fd442, 0d0000000000000000;
	mul.rn.f64 	%fd665, %fd626, %fd442;

$L__BB0_49:
	setp.gt.s32 	%p31, %r18, -1;
	@%p31 bra 	$L__BB0_51;

	mov.f64 	%fd443, 0d7FF0000000000000;
	mul.rn.f64 	%fd665, %fd665, %fd443;

$L__BB0_51:
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r165}, %fd14;
	}
	setp.gt.s32 	%p32, %r165, -1;
	@%p32 bra 	$L__BB0_56;

	mov.f64 	%fd444, 0dBCA1A62633145C07;
	add.rn.f64 	%fd445, %fd665, %fd444;
	neg.f64 	%fd446, %fd445;
	mov.f64 	%fd447, 0d400921FB54442D18;
	add.rn.f64 	%fd665, %fd447, %fd446;

$L__BB0_56:
	add.f64 	%fd481, %fd665, 0d402921FB54442D18;
	div.rn.f64 	%fd76, %fd481, 0d4008000000000000;
	{
	.reg .b32 %temp; 
	mov.b64 	{%r110, %temp}, %fd76;
	}
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r111}, %fd76;
	}
	and.b32  	%r112, %r111, 2147483647;
	setp.eq.s32 	%p34, %r112, 2146435072;
	setp.eq.s32 	%p35, %r110, 0;
	and.pred  	%p36, %p35, %p34;
	@%p36 bra 	$L__BB0_60;
	bra.uni 	$L__BB0_57;

$L__BB0_60:
	mov.f64 	%fd491, 0d0000000000000000;
	mul.rn.f64 	%fd667, %fd76, %fd491;
	mov.u32 	%r185, 1;
	bra.uni 	$L__BB0_61;

$L__BB0_57:
	add.u64 	%rd92, %SPL, 0;
	mul.f64 	%fd482, %fd76, 0d3FE45F306DC9C883;
	cvt.rni.s32.f64 	%r184, %fd482;
	st.local.u32 	[%rd92], %r184;
	cvt.rn.f64.s32 	%fd483, %r184;
	neg.f64 	%fd484, %fd483;
	mov.f64 	%fd485, 0d3FF921FB54442D18;
	fma.rn.f64 	%fd486, %fd484, %fd485, %fd76;
	mov.f64 	%fd487, 0d3C91A62633145C00;
	fma.rn.f64 	%fd488, %fd484, %fd487, %fd486;
	mov.f64 	%fd489, 0d397B839A252049C0;
	fma.rn.f64 	%fd667, %fd484, %fd489, %fd488;
	abs.f64 	%fd490, %fd76;
	setp.ltu.f64 	%p37, %fd490, 0d41E0000000000000;
	@%p37 bra 	$L__BB0_59;

	add.u64 	%rd94, %SPL, 0;
	add.u64 	%rd84, %SP, 0;
	{ // callseq 2, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.f64 	[param0+0], %fd76;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd84;
	.param .b64 retval0;
	call.uni (retval0), 
	__internal_trig_reduction_slowpathd, 
	(
	param0, 
	param1
	);
	ld.param.f64 	%fd667, [retval0+0];
	} // callseq 2
	ld.local.u32 	%r184, [%rd94];

$L__BB0_59:
	add.s32 	%r185, %r184, 1;

$L__BB0_61:
	mov.u64 	%rd96, __cudart_sin_cos_coeffs;
	and.b32  	%r114, %r185, 1;
	shl.b32 	%r115, %r185, 3;
	and.b32  	%r116, %r115, 8;
	setp.eq.s32 	%p38, %r114, 0;
	selp.f64 	%fd492, 0d3DE5DB65F9785EBA, 0dBDA8FF8320FD8164, %p38;
	mul.wide.s32 	%rd54, %r116, 8;
	add.s64 	%rd56, %rd96, %rd54;
	ld.global.nc.f64 	%fd493, [%rd56+8];
	mul.rn.f64 	%fd82, %fd667, %fd667;
	fma.rn.f64 	%fd494, %fd492, %fd82, %fd493;
	ld.global.nc.f64 	%fd495, [%rd56+16];
	fma.rn.f64 	%fd496, %fd494, %fd82, %fd495;
	ld.global.nc.f64 	%fd497, [%rd56+24];
	fma.rn.f64 	%fd498, %fd496, %fd82, %fd497;
	ld.global.nc.f64 	%fd499, [%rd56+32];
	fma.rn.f64 	%fd500, %fd498, %fd82, %fd499;
	ld.global.nc.f64 	%fd501, [%rd56+40];
	fma.rn.f64 	%fd502, %fd500, %fd82, %fd501;
	ld.global.nc.f64 	%fd503, [%rd56+48];
	fma.rn.f64 	%fd83, %fd502, %fd82, %fd503;
	fma.rn.f64 	%fd669, %fd83, %fd667, %fd667;
	@%p38 bra 	$L__BB0_63;

	mov.f64 	%fd504, 0d3FF0000000000000;
	fma.rn.f64 	%fd669, %fd83, %fd82, %fd504;

$L__BB0_63:
	and.b32  	%r117, %r185, 2;
	setp.eq.s32 	%p39, %r117, 0;
	@%p39 bra 	$L__BB0_65;

	mov.f64 	%fd505, 0d0000000000000000;
	mov.f64 	%fd506, 0dBFF0000000000000;
	fma.rn.f64 	%fd669, %fd669, %fd506, %fd505;

$L__BB0_65:
	fma.rn.f64 	%fd670, %fd12, %fd669, %fd13;
	st.local.f64 	[%rd2+16], %fd670;

$L__BB0_68:
	setp.geu.f64 	%p40, %fd672, %fd671;
	mov.f64 	%fd678, %fd671;
	@%p40 bra 	$L__BB0_70;

	st.local.f64 	[%rd2], %fd671;
	st.local.f64 	[%rd2+8], %fd672;
	mov.f64 	%fd678, %fd672;
	mov.f64 	%fd672, %fd671;

$L__BB0_70:
	setp.geu.f64 	%p41, %fd672, %fd670;
	mov.f64 	%fd675, %fd672;
	@%p41 bra 	$L__BB0_72;

	st.local.f64 	[%rd2], %fd670;
	st.local.f64 	[%rd2+16], %fd672;
	mov.f64 	%fd675, %fd670;
	mov.f64 	%fd670, %fd672;

$L__BB0_72:
	setp.geu.f64 	%p42, %fd678, %fd670;
	mov.f64 	%fd677, %fd670;
	@%p42 bra 	$L__BB0_74;

	st.local.f64 	[%rd2+8], %fd670;
	st.local.f64 	[%rd2+16], %fd678;
	mov.f64 	%fd677, %fd678;
	mov.f64 	%fd678, %fd670;

$L__BB0_74:
	ld.param.u32 	%r166, [eigenBatchKernel_param_18];
	cvt.rn.f32.f64 	%f13, %fd675;
	st.global.f32 	[%rd5], %f13;
	cvt.rn.f32.f64 	%f14, %fd678;
	st.global.f32 	[%rd5+4], %f14;
	cvt.rn.f32.f64 	%f15, %fd677;
	st.global.f32 	[%rd5+8], %f15;
	mul.wide.s32 	%rd57, %r166, 8;
	add.s64 	%rd58, %rd2, %rd57;
	ld.local.f64 	%fd679, [%rd58];

$L__BB0_75:
	ld.param.u32 	%r167, [eigenBatchKernel_param_20];
	sub.f64 	%fd691, %fd2, %fd679;
	st.local.f64 	[%rd4+-72], %fd691;
	sub.f64 	%fd685, %fd5, %fd679;
	st.local.f64 	[%rd4+-40], %fd685;
	sub.f64 	%fd680, %fd7, %fd679;
	st.local.f64 	[%rd4+-8], %fd680;
	mad.lo.s32 	%r24, %r2, %r167, %r3;
	abs.f64 	%fd507, %fd691;
	abs.f64 	%fd689, %fd692;
	setp.gt.f64 	%p44, %fd689, %fd507;
	selp.u32 	%r118, 1, 0, %p44;
	selp.f64 	%fd508, %fd689, %fd507, %p44;
	abs.f64 	%fd509, %fd690;
	setp.gt.f64 	%p45, %fd509, %fd508;
	selp.b32 	%r25, 2, %r118, %p45;
	selp.f64 	%fd510, %fd509, %fd508, %p45;
	setp.le.f64 	%p46, %fd510, %fd1;
	mov.pred 	%p86, 0;
	@%p46 bra 	$L__BB0_79;

	setp.eq.s32 	%p47, %r25, 0;
	mov.f64 	%fd683, %fd681;
	mov.f64 	%fd684, %fd690;
	mov.f64 	%fd688, %fd692;
	@%p47 bra 	$L__BB0_78;

	mul.wide.u32 	%rd59, %r25, 24;
	add.s64 	%rd60, %rd3, %rd59;
	ld.local.f64 	%fd109, [%rd60];
	st.local.f64 	[%rd60], %fd691;
	st.local.f64 	[%rd4+-72], %fd109;
	ld.local.f64 	%fd110, [%rd60+8];
	st.local.f64 	[%rd60+8], %fd692;
	st.local.f64 	[%rd4+-64], %fd110;
	ld.local.f64 	%fd684, [%rd60+16];
	st.local.f64 	[%rd60+16], %fd690;
	st.local.f64 	[%rd4+-56], %fd684;
	ld.local.f64 	%fd688, [%rd4+-48];
	ld.local.f64 	%fd685, [%rd4+-40];
	ld.local.f64 	%fd683, [%rd4+-32];
	ld.local.f64 	%fd690, [%rd4+-24];
	ld.local.f64 	%fd681, [%rd4+-16];
	ld.local.f64 	%fd680, [%rd4+-8];
	mov.f64 	%fd692, %fd110;
	mov.f64 	%fd691, %fd109;

$L__BB0_78:
	div.rn.f64 	%fd511, %fd688, %fd691;
	mul.f64 	%fd512, %fd511, %fd691;
	sub.f64 	%fd127, %fd688, %fd512;
	st.local.f64 	[%rd4+-48], %fd127;
	mul.f64 	%fd513, %fd511, %fd692;
	sub.f64 	%fd128, %fd685, %fd513;
	st.local.f64 	[%rd4+-40], %fd128;
	mul.f64 	%fd514, %fd511, %fd684;
	sub.f64 	%fd129, %fd683, %fd514;
	st.local.f64 	[%rd4+-32], %fd129;
	div.rn.f64 	%fd515, %fd690, %fd691;
	mul.f64 	%fd516, %fd515, %fd691;
	sub.f64 	%fd517, %fd690, %fd516;
	st.local.f64 	[%rd4+-24], %fd517;
	mul.f64 	%fd518, %fd515, %fd692;
	sub.f64 	%fd519, %fd681, %fd518;
	st.local.f64 	[%rd4+-16], %fd519;
	mul.f64 	%fd520, %fd515, %fd684;
	sub.f64 	%fd521, %fd680, %fd520;
	st.local.f64 	[%rd4+-8], %fd521;
	abs.f64 	%fd689, %fd128;
	mov.pred 	%p86, -1;
	mov.f64 	%fd690, %fd129;
	mov.f64 	%fd691, %fd127;
	mov.f64 	%fd692, %fd128;

$L__BB0_79:
	selp.u64 	%rd7, 1, 0, %p86;
	selp.b32 	%r119, 2, 1, %p86;
	cvt.u64.u32 	%rd8, %r119;
	mul.wide.s32 	%rd61, %r119, 24;
	add.s64 	%rd9, %rd3, %rd61;
	ld.local.f64 	%fd697, [%rd9+8];
	abs.f64 	%fd522, %fd697;
	setp.gt.f64 	%p49, %fd522, %fd689;
	selp.u32 	%r26, 1, 0, %p86;
	selp.b32 	%r186, %r119, %r26, %p49;
	selp.f64 	%fd693, %fd522, %fd689, %p49;
	@%p86 bra 	$L__BB0_81;

	cvt.u32.u64 	%r120, %rd8;
	add.s32 	%r121, %r120, 1;
	ld.local.f64 	%fd523, [%rd9+32];
	abs.f64 	%fd524, %fd523;
	setp.gt.f64 	%p50, %fd524, %fd693;
	selp.b32 	%r186, %r121, %r186, %p50;
	selp.f64 	%fd693, %fd524, %fd693, %p50;

$L__BB0_81:
	ld.local.f64 	%fd525, [%rd4];
	setp.le.f64 	%p52, %fd693, %fd525;
	mov.pred 	%p87, 0;
	@%p52 bra 	$L__BB0_87;

	setp.eq.s32 	%p53, %r186, %r26;
	mul.lo.s64 	%rd62, %rd7, 24;
	add.s64 	%rd10, %rd3, %rd62;
	@%p53 bra 	$L__BB0_84;
	bra.uni 	$L__BB0_83;

$L__BB0_84:
	mov.f64 	%fd694, %fd690;
	mov.f64 	%fd695, %fd691;
	mov.f64 	%fd696, %fd692;
	bra.uni 	$L__BB0_85;

$L__BB0_83:
	mul.wide.u32 	%rd63, %r186, 24;
	add.s64 	%rd64, %rd3, %rd63;
	ld.local.f64 	%fd695, [%rd64];
	st.local.f64 	[%rd64], %fd691;
	st.local.f64 	[%rd10], %fd695;
	ld.local.f64 	%fd696, [%rd64+8];
	st.local.f64 	[%rd64+8], %fd692;
	st.local.f64 	[%rd10+8], %fd696;
	ld.local.f64 	%fd694, [%rd64+16];
	st.local.f64 	[%rd64+16], %fd690;
	st.local.f64 	[%rd10+16], %fd694;
	ld.local.f64 	%fd697, [%rd9+8];

$L__BB0_85:
	div.rn.f64 	%fd526, %fd697, %fd696;
	mul.f64 	%fd527, %fd526, %fd695;
	ld.local.f64 	%fd528, [%rd9];
	sub.f64 	%fd529, %fd528, %fd527;
	st.local.f64 	[%rd9], %fd529;
	mul.f64 	%fd530, %fd526, %fd696;
	sub.f64 	%fd531, %fd697, %fd530;
	st.local.f64 	[%rd9+8], %fd531;
	mul.f64 	%fd532, %fd526, %fd694;
	ld.local.f64 	%fd533, [%rd9+16];
	sub.f64 	%fd534, %fd533, %fd532;
	st.local.f64 	[%rd9+16], %fd534;
	mov.pred 	%p87, -1;
	@%p86 bra 	$L__BB0_87;

	ld.local.f64 	%fd535, [%rd10+8];
	ld.local.f64 	%fd536, [%rd9+32];
	div.rn.f64 	%fd537, %fd536, %fd535;
	ld.local.f64 	%fd538, [%rd10];
	mul.f64 	%fd539, %fd537, %fd538;
	ld.local.f64 	%fd540, [%rd9+24];
	sub.f64 	%fd541, %fd540, %fd539;
	st.local.f64 	[%rd9+24], %fd541;
	mul.f64 	%fd542, %fd537, %fd535;
	sub.f64 	%fd543, %fd536, %fd542;
	st.local.f64 	[%rd9+32], %fd543;
	ld.local.f64 	%fd544, [%rd10+16];
	mul.f64 	%fd545, %fd537, %fd544;
	ld.local.f64 	%fd546, [%rd9+40];
	sub.f64 	%fd547, %fd546, %fd545;
	st.local.f64 	[%rd9+40], %fd547;

$L__BB0_87:
	not.pred 	%p56, %p87;
	selp.u32 	%r122, 1, 0, %p56;
	not.pred 	%p57, %p86;
	selp.u32 	%r123, 1, 0, %p57;
	add.s32 	%r30, %r123, %r122;
	selp.u32 	%r31, 1, 0, %p87;
	add.s32 	%r32, %r26, %r31;
	mul.wide.u32 	%rd65, %r32, 24;
	add.s64 	%rd11, %rd3, %rd65;
	ld.local.f64 	%fd699, [%rd11+16];
	abs.f64 	%fd698, %fd699;
	setp.gt.u32 	%p58, %r32, 1;
	mov.u32 	%r187, %r32;
	@%p58 bra 	$L__BB0_90;

	add.s32 	%r124, %r32, 1;
	ld.local.f64 	%fd548, [%rd11+40];
	abs.f64 	%fd549, %fd548;
	setp.gt.f64 	%p59, %fd549, %fd698;
	selp.b32 	%r187, %r124, %r32, %p59;
	selp.f64 	%fd698, %fd549, %fd698, %p59;
	setp.gt.u32 	%p60, %r124, 1;
	@%p60 bra 	$L__BB0_90;

	add.s32 	%r125, %r32, 2;
	ld.local.f64 	%fd550, [%rd11+64];
	abs.f64 	%fd551, %fd550;
	setp.gt.f64 	%p61, %fd551, %fd698;
	selp.b32 	%r187, %r125, %r187, %p61;
	selp.f64 	%fd698, %fd551, %fd698, %p61;

$L__BB0_90:
	ld.local.f64 	%fd552, [%rd4];
	setp.le.f64 	%p62, %fd698, %fd552;
	mov.u32 	%r188, 1;
	@%p62 bra 	$L__BB0_96;

	setp.eq.s32 	%p63, %r187, %r32;
	mul.lo.s64 	%rd66, %rd7, 24;
	add.s64 	%rd67, %rd3, %rd66;
	mul.wide.u32 	%rd68, %r31, 24;
	add.s64 	%rd69, %rd67, %rd68;
	add.s64 	%rd12, %rd69, 8;
	@%p63 bra 	$L__BB0_93;

	mul.wide.u32 	%rd70, %r187, 24;
	add.s64 	%rd71, %rd3, %rd70;
	ld.local.f64 	%fd553, [%rd71];
	ld.local.f64 	%fd554, [%rd11];
	st.local.f64 	[%rd71], %fd554;
	st.local.f64 	[%rd11], %fd553;
	ld.local.f64 	%fd555, [%rd71+8];
	ld.local.f64 	%fd556, [%rd12];
	st.local.f64 	[%rd71+8], %fd556;
	st.local.f64 	[%rd12], %fd555;
	ld.local.f64 	%fd152, [%rd71+16];
	st.local.f64 	[%rd71+16], %fd699;
	st.local.f64 	[%rd11+16], %fd152;
	mov.f64 	%fd699, %fd152;

$L__BB0_93:
	mov.u32 	%r188, 0;
	@%p58 bra 	$L__BB0_96;

	add.s32 	%r129, %r32, 1;
	ld.local.f64 	%fd557, [%rd11+40];
	div.rn.f64 	%fd558, %fd557, %fd699;
	ld.local.f64 	%fd154, [%rd11];
	mul.f64 	%fd559, %fd558, %fd154;
	ld.local.f64 	%fd560, [%rd11+24];
	sub.f64 	%fd561, %fd560, %fd559;
	st.local.f64 	[%rd11+24], %fd561;
	ld.local.f64 	%fd155, [%rd12];
	mul.f64 	%fd562, %fd558, %fd155;
	ld.local.f64 	%fd563, [%rd12+24];
	sub.f64 	%fd564, %fd563, %fd562;
	st.local.f64 	[%rd12+24], %fd564;
	mul.f64 	%fd565, %fd558, %fd699;
	sub.f64 	%fd566, %fd557, %fd565;
	st.local.f64 	[%rd11+40], %fd566;
	setp.gt.u32 	%p65, %r129, 1;
	@%p65 bra 	$L__BB0_96;

	ld.local.f64 	%fd567, [%rd11+64];
	div.rn.f64 	%fd568, %fd567, %fd699;
	mul.f64 	%fd569, %fd568, %fd154;
	ld.local.f64 	%fd570, [%rd11+48];
	sub.f64 	%fd571, %fd570, %fd569;
	st.local.f64 	[%rd11+48], %fd571;
	mul.f64 	%fd572, %fd568, %fd155;
	ld.local.f64 	%fd573, [%rd12+48];
	sub.f64 	%fd574, %fd573, %fd572;
	st.local.f64 	[%rd12+48], %fd574;
	mul.f64 	%fd575, %fd568, %fd699;
	sub.f64 	%fd576, %fd567, %fd575;
	st.local.f64 	[%rd11+64], %fd576;

$L__BB0_96:
	ld.param.u64 	%rd85, [eigenBatchKernel_param_19];
	cvta.to.global.u64 	%rd72, %rd85;
	mul.wide.s32 	%rd73, %r24, 4;
	add.s64 	%rd13, %rd72, %rd73;
	add.s32 	%r131, %r30, %r188;
	cvt.u16.u32 	%rs1, %r131;
	setp.eq.s16 	%p66, %rs1, 1;
	@%p66 bra 	$L__BB0_116;

	setp.eq.s16 	%p67, %rs1, 2;
	@%p67 bra 	$L__BB0_105;

	setp.ne.s16 	%p68, %rs1, 3;
	@%p68 bra 	$L__BB0_121;

	ld.param.u32 	%r170, [eigenBatchKernel_param_18];
	setp.eq.s32 	%p69, %r170, 0;
	@%p69 bra 	$L__BB0_104;

	ld.param.u32 	%r171, [eigenBatchKernel_param_18];
	setp.eq.s32 	%p70, %r171, 1;
	@%p70 bra 	$L__BB0_103;

	ld.param.u32 	%r172, [eigenBatchKernel_param_18];
	setp.ne.s32 	%p71, %r172, 2;
	@%p71 bra 	$L__BB0_121;

	mov.u32 	%r132, 0;
	st.global.u32 	[%rd13], %r132;
	st.global.u32 	[%rd13+4], %r132;
	mov.u32 	%r133, 1065353216;
	st.global.u32 	[%rd13+8], %r133;
	bra.uni 	$L__BB0_121;

$L__BB0_116:
	ld.local.f64 	%fd158, [%rd4+-72];
	abs.f64 	%fd588, %fd158;
	setp.gtu.f64 	%p80, %fd588, %fd1;
	@%p80 bra 	$L__BB0_118;
	bra.uni 	$L__BB0_117;

$L__BB0_118:
	ld.local.f64 	%fd159, [%rd4+-40];
	abs.f64 	%fd589, %fd159;
	setp.gtu.f64 	%p81, %fd589, %fd1;
	@%p81 bra 	$L__BB0_120;
	bra.uni 	$L__BB0_119;

$L__BB0_120:
	mov.u32 	%r155, 1065353216;
	st.global.u32 	[%rd13+8], %r155;
	ld.local.f64 	%fd593, [%rd4+-32];
	neg.f64 	%fd594, %fd593;
	div.rn.f64 	%fd595, %fd594, %fd159;
	cvt.rn.f32.f64 	%f20, %fd595;
	st.global.f32 	[%rd13+4], %f20;
	ld.local.f64 	%fd596, [%rd4+-56];
	neg.f64 	%fd597, %fd596;
	cvt.f64.f32 	%fd598, %f20;
	ld.local.f64 	%fd599, [%rd4+-64];
	mul.f64 	%fd600, %fd599, %fd598;
	sub.f64 	%fd601, %fd597, %fd600;
	div.rn.f64 	%fd602, %fd601, %fd158;
	cvt.rn.f32.f64 	%f21, %fd602;
	st.global.f32 	[%rd13], %f21;
	bra.uni 	$L__BB0_121;

$L__BB0_105:
	ld.local.f64 	%fd156, [%rd4+-72];
	abs.f64 	%fd577, %fd156;
	setp.gtu.f64 	%p72, %fd577, %fd1;
	@%p72 bra 	$L__BB0_113;
	bra.uni 	$L__BB0_106;

$L__BB0_113:
	ld.param.u32 	%r174, [eigenBatchKernel_param_18];
	and.b32  	%r146, %r174, 1;
	setp.eq.b32 	%p76, %r146, 1;
	mov.pred 	%p77, 0;
	xor.pred  	%p78, %p76, %p77;
	not.pred 	%p79, %p78;
	@%p79 bra 	$L__BB0_115;
	bra.uni 	$L__BB0_114;

$L__BB0_115:
	ld.local.f64 	%fd585, [%rd4+-64];
	neg.f64 	%fd586, %fd585;
	div.rn.f64 	%fd587, %fd586, %fd156;
	cvt.rn.f32.f64 	%f18, %fd587;
	st.global.f32 	[%rd13], %f18;
	mov.u32 	%r149, 1065353216;
	st.global.u32 	[%rd13+4], %r149;
	mov.u32 	%r150, 0;
	st.global.u32 	[%rd13+8], %r150;
	bra.uni 	$L__BB0_121;

$L__BB0_117:
	mov.u32 	%r151, 1065353216;
	st.global.u32 	[%rd13], %r151;
	mov.u32 	%r152, 0;
	st.global.u32 	[%rd13+4], %r152;
	st.global.u32 	[%rd13+8], %r152;
	bra.uni 	$L__BB0_121;

$L__BB0_106:
	ld.param.u32 	%r173, [eigenBatchKernel_param_18];
	ld.local.f64 	%fd157, [%rd4+-64];
	abs.f64 	%fd578, %fd157;
	setp.gtu.f64 	%p73, %fd578, %fd1;
	and.b32  	%r37, %r173, 1;
	@%p73 bra 	$L__BB0_110;
	bra.uni 	$L__BB0_107;

$L__BB0_110:
	setp.eq.s32 	%p75, %r37, 0;
	@%p75 bra 	$L__BB0_112;
	bra.uni 	$L__BB0_111;

$L__BB0_112:
	ld.local.f64 	%fd579, [%rd4+-56];
	neg.f64 	%fd580, %fd579;
	div.rn.f64 	%fd581, %fd580, %fd157;
	cvt.rn.f32.f64 	%f16, %fd581;
	mov.u32 	%r144, 0;
	st.global.u32 	[%rd13], %r144;
	st.global.f32 	[%rd13+4], %f16;
	mov.u32 	%r145, 1065353216;
	st.global.u32 	[%rd13+8], %r145;
	bra.uni 	$L__BB0_121;

$L__BB0_104:
	mov.u32 	%r136, 1065353216;
	st.global.u32 	[%rd13], %r136;
	mov.u32 	%r137, 0;
	st.global.u32 	[%rd13+4], %r137;
	st.global.u32 	[%rd13+8], %r137;
	bra.uni 	$L__BB0_121;

$L__BB0_103:
	mov.u32 	%r134, 0;
	st.global.u32 	[%rd13], %r134;
	mov.u32 	%r135, 1065353216;
	st.global.u32 	[%rd13+4], %r135;
	st.global.u32 	[%rd13+8], %r134;
	bra.uni 	$L__BB0_121;

$L__BB0_119:
	ld.local.f64 	%fd590, [%rd4+-64];
	neg.f64 	%fd591, %fd590;
	div.rn.f64 	%fd592, %fd591, %fd158;
	cvt.rn.f32.f64 	%f19, %fd592;
	st.global.f32 	[%rd13], %f19;
	mov.u32 	%r153, 1065353216;
	st.global.u32 	[%rd13+4], %r153;
	mov.u32 	%r154, 0;
	st.global.u32 	[%rd13+8], %r154;
	bra.uni 	$L__BB0_121;

$L__BB0_114:
	ld.local.f64 	%fd582, [%rd4+-56];
	neg.f64 	%fd583, %fd582;
	div.rn.f64 	%fd584, %fd583, %fd156;
	cvt.rn.f32.f64 	%f17, %fd584;
	st.global.f32 	[%rd13], %f17;
	mov.u32 	%r147, 0;
	st.global.u32 	[%rd13+4], %r147;
	mov.u32 	%r148, 1065353216;
	st.global.u32 	[%rd13+8], %r148;
	bra.uni 	$L__BB0_121;

$L__BB0_107:
	setp.eq.s32 	%p74, %r37, 0;
	@%p74 bra 	$L__BB0_109;
	bra.uni 	$L__BB0_108;

$L__BB0_109:
	mov.u32 	%r140, 1065353216;
	st.global.u32 	[%rd13], %r140;
	mov.u32 	%r141, 0;
	st.global.u32 	[%rd13+4], %r141;
	st.global.u32 	[%rd13+8], %r141;
	bra.uni 	$L__BB0_121;

$L__BB0_111:
	mov.u32 	%r142, 1065353216;
	st.global.u32 	[%rd13], %r142;
	mov.u32 	%r143, 0;
	st.global.u32 	[%rd13+4], %r143;
	st.global.u32 	[%rd13+8], %r143;
	bra.uni 	$L__BB0_121;

$L__BB0_108:
	mov.u32 	%r138, 0;
	st.global.u32 	[%rd13], %r138;
	mov.u32 	%r139, 1065353216;
	st.global.u32 	[%rd13+4], %r139;
	st.global.u32 	[%rd13+8], %r138;

$L__BB0_121:
	ld.param.u32 	%r168, [eigenBatchKernel_param_13];
	mad.lo.s32 	%r156, %r168, 1000, 580;
	setp.eq.s32 	%p82, %r1, %r156;
	@%p82 bra 	$L__BB0_122;
	bra.uni 	$L__BB0_123;

$L__BB0_122:
	add.u64 	%rd86, %SP, 8;
	ld.param.u32 	%r169, [eigenBatchKernel_param_13];
	ld.global.f32 	%f22, [%rd13];
	ld.global.f32 	%f23, [%rd13+4];
	ld.global.f32 	%f24, [%rd13+8];
	div.s32 	%r157, %r1, %r169;
	add.u64 	%rd74, %SP, 160;
	add.u64 	%rd75, %SPL, 160;
	st.local.v2.u32 	[%rd75], {%r1, %r157};
	mul.lo.s32 	%r158, %r157, %r169;
	sub.s32 	%r159, %r1, %r158;
	st.local.u32 	[%rd75+8], %r159;
	cvt.f64.f32 	%fd603, %f23;
	cvt.f64.f32 	%fd604, %f22;
	st.local.v2.f64 	[%rd75+16], {%fd604, %fd603};
	cvt.f64.f32 	%fd605, %f24;
	st.local.v2.f64 	[%rd75+32], {%fd605, %fd1};
	mov.u64 	%rd76, $str;
	cvta.global.u64 	%rd77, %rd76;
	{ // callseq 3, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd77;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd74;
	.param .b32 retval0;
	call.uni (retval0), 
	vprintf, 
	(
	param0, 
	param1
	);
	ld.param.b32 	%r160, [retval0+0];
	} // callseq 3
	ld.local.f64 	%fd606, [%rd4+-72];
	ld.local.f64 	%fd607, [%rd4+-64];
	ld.local.f64 	%fd608, [%rd4+-56];
	ld.local.f64 	%fd609, [%rd4+-48];
	ld.local.f64 	%fd610, [%rd4+-40];
	ld.local.f64 	%fd611, [%rd4+-32];
	ld.local.f64 	%fd612, [%rd4+-24];
	ld.local.f64 	%fd613, [%rd4+-16];
	ld.local.f64 	%fd614, [%rd4+-8];
	st.local.f64 	[%rd2], %fd606;
	st.local.f64 	[%rd2+8], %fd607;
	st.local.f64 	[%rd2+16], %fd608;
	st.local.f64 	[%rd2+24], %fd609;
	st.local.f64 	[%rd2+32], %fd610;
	st.local.f64 	[%rd2+40], %fd611;
	st.local.f64 	[%rd2+48], %fd612;
	st.local.f64 	[%rd2+56], %fd613;
	st.local.f64 	[%rd2+64], %fd614;
	mov.u64 	%rd80, $str$1;
	cvta.global.u64 	%rd81, %rd80;
	{ // callseq 4, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd81;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd86;
	.param .b32 retval0;
	call.uni (retval0), 
	vprintf, 
	(
	param0, 
	param1
	);
	ld.param.b32 	%r161, [retval0+0];
	} // callseq 4

$L__BB0_123:
	ld.global.f32 	%f1, [%rd13];
	ld.global.f32 	%f2, [%rd13+4];
	mul.f32 	%f25, %f2, %f2;
	fma.rn.f32 	%f26, %f1, %f1, %f25;
	ld.global.f32 	%f3, [%rd13+8];
	fma.rn.f32 	%f27, %f3, %f3, %f26;
	sqrt.rn.f32 	%f4, %f27;
	setp.leu.f32 	%p83, %f4, 0f00000000;
	@%p83 bra 	$L__BB0_125;

	cvt.f64.f32 	%fd615, %f4;
	rcp.rn.f64 	%fd616, %fd615;
	cvt.f64.f32 	%fd617, %f1;
	mul.f64 	%fd618, %fd616, %fd617;
	cvt.rn.f32.f64 	%f28, %fd618;
	st.global.f32 	[%rd13], %f28;
	cvt.f64.f32 	%fd619, %f2;
	mul.f64 	%fd620, %fd616, %fd619;
	cvt.rn.f32.f64 	%f29, %fd620;
	st.global.f32 	[%rd13+4], %f29;
	cvt.f64.f32 	%fd621, %f3;
	mul.f64 	%fd622, %fd616, %fd621;
	cvt.rn.f32.f64 	%f30, %fd622;
	st.global.f32 	[%rd13+8], %f30;

$L__BB0_125:
	ret;

}
.func  (.param .b64 func_retval0) __internal_trig_reduction_slowpathd(
	.param .b64 __internal_trig_reduction_slowpathd_param_0,
	.param .b64 __internal_trig_reduction_slowpathd_param_1
)
{
	.local .align 8 .b8 	__local_depot1[40];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<10>;
	.reg .b32 	%r<33>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<80>;


	mov.u64 	%SPL, __local_depot1;
	ld.param.f64 	%fd4, [__internal_trig_reduction_slowpathd_param_0];
	ld.param.u64 	%rd18, [__internal_trig_reduction_slowpathd_param_1];
	add.u64 	%rd1, %SPL, 0;
	{
	.reg .b32 %temp; 
	mov.b64 	{%temp, %r1}, %fd4;
	}
	bfe.u32 	%r2, %r1, 20, 11;
	setp.eq.s32 	%p1, %r2, 2047;
	@%p1 bra 	$L__BB1_7;

	add.s32 	%r3, %r2, -1024;
	shr.u32 	%r10, %r3, 6;
	mov.u32 	%r11, 16;
	sub.s32 	%r12, %r11, %r10;
	mov.u32 	%r13, 15;
	sub.s32 	%r4, %r13, %r10;
	mov.u32 	%r14, 19;
	sub.s32 	%r15, %r14, %r10;
	setp.gt.s32 	%p2, %r12, 14;
	selp.b32 	%r5, 18, %r15, %p2;
	setp.gt.s32 	%p3, %r12, %r5;
	mov.u64 	%rd77, 0;
	mov.u32 	%r32, %r4;
	@%p3 bra 	$L__BB1_4;

	add.s32 	%r16, %r4, -15;
	mul.wide.s32 	%rd22, %r16, 8;
	mov.u64 	%rd23, __cudart_i2opi_d;
	add.s64 	%rd24, %rd23, %rd22;
	add.s64 	%rd75, %rd24, 120;
	mov.b64 	%rd25, %fd4;
	shl.b64 	%rd26, %rd25, 11;
	or.b64  	%rd3, %rd26, -9223372036854775808;
	mov.u64 	%rd74, %rd1;
	mov.u32 	%r32, %r4;

$L__BB1_3:
	.pragma "nounroll";
	ld.global.nc.u64 	%rd27, [%rd75];
	{
	.reg .u32 %r0, %r1, %r2, %r3, %alo, %ahi, %blo, %bhi, %clo, %chi;
	mov.b64 	{%alo,%ahi}, %rd27;
	mov.b64 	{%blo,%bhi}, %rd3;
	mov.b64 	{%clo,%chi}, %rd77;
	mad.lo.cc.u32 	%r0, %alo, %blo, %clo;
	madc.hi.cc.u32 	%r1, %alo, %blo, %chi;
	madc.hi.u32 	%r2, %alo, %bhi, 0;
	mad.lo.cc.u32 	%r1, %alo, %bhi, %r1;
	madc.hi.cc.u32 	%r2, %ahi, %blo, %r2;
	madc.hi.u32 	%r3, %ahi, %bhi, 0;
	mad.lo.cc.u32 	%r1, %ahi, %blo, %r1;
	madc.lo.cc.u32 	%r2, %ahi, %bhi, %r2;
	addc.u32 	%r3, %r3, 0;
	mov.b64 	%rd28, {%r0,%r1};
	mov.b64 	%rd77, {%r2,%r3};
	}
	st.local.u64 	[%rd74], %rd28;
	add.s64 	%rd75, %rd75, 8;
	add.s64 	%rd74, %rd74, 8;
	add.s32 	%r32, %r32, 1;
	setp.lt.s32 	%p4, %r32, %r5;
	@%p4 bra 	$L__BB1_3;

$L__BB1_4:
	sub.s32 	%r17, %r32, %r4;
	mul.wide.s32 	%rd29, %r17, 8;
	add.s64 	%rd30, %rd1, %rd29;
	st.local.u64 	[%rd30], %rd77;
	ld.local.u64 	%rd79, [%rd1+16];
	ld.local.u64 	%rd78, [%rd1+24];
	and.b32  	%r9, %r3, 63;
	setp.eq.s32 	%p5, %r9, 0;
	@%p5 bra 	$L__BB1_6;

	mov.u32 	%r18, 64;
	sub.s32 	%r19, %r18, %r9;
	shl.b64 	%rd31, %rd78, %r9;
	shr.u64 	%rd32, %rd79, %r19;
	or.b64  	%rd78, %rd31, %rd32;
	shl.b64 	%rd33, %rd79, %r9;
	ld.local.u64 	%rd34, [%rd1+8];
	shr.u64 	%rd35, %rd34, %r19;
	or.b64  	%rd79, %rd35, %rd33;

$L__BB1_6:
	and.b32  	%r20, %r1, -2147483648;
	shr.u64 	%rd36, %rd78, 62;
	cvt.u32.u64 	%r21, %rd36;
	shr.u64 	%rd37, %rd79, 62;
	shl.b64 	%rd38, %rd78, 2;
	or.b64  	%rd39, %rd37, %rd38;
	shr.u64 	%rd40, %rd78, 61;
	cvt.u32.u64 	%r22, %rd40;
	and.b32  	%r23, %r22, 1;
	add.s32 	%r24, %r23, %r21;
	neg.s32 	%r25, %r24;
	setp.eq.s32 	%p6, %r20, 0;
	selp.b32 	%r26, %r24, %r25, %p6;
	cvta.to.local.u64 	%rd41, %rd18;
	mov.u64 	%rd42, 0;
	st.local.u32 	[%rd41], %r26;
	setp.eq.s32 	%p7, %r23, 0;
	shl.b64 	%rd43, %rd79, 2;
	{
	.reg .u32 %r0, %r1, %r2, %r3, %a0, %a1, %a2, %a3, %b0, %b1, %b2, %b3;
	mov.b64 	{%a0,%a1}, %rd42;
	mov.b64 	{%a2,%a3}, %rd42;
	mov.b64 	{%b0,%b1}, %rd43;
	mov.b64 	{%b2,%b3}, %rd39;
	sub.cc.u32 	%r0, %a0, %b0;
	subc.cc.u32 	%r1, %a1, %b1;
	subc.cc.u32 	%r2, %a2, %b2;
	subc.u32 	%r3, %a3, %b3;
	mov.b64 	%rd44, {%r0,%r1};
	mov.b64 	%rd45, {%r2,%r3};
	}
	selp.b64 	%rd46, %rd39, %rd45, %p7;
	selp.b64 	%rd47, %rd43, %rd44, %p7;
	xor.b32  	%r27, %r20, -2147483648;
	selp.b32 	%r28, %r20, %r27, %p7;
	clz.b64 	%r29, %rd46;
	cvt.u64.u32 	%rd48, %r29;
	setp.eq.s64 	%p8, %rd48, 0;
	shl.b64 	%rd49, %rd46, %r29;
	mov.u64 	%rd50, 64;
	sub.s64 	%rd51, %rd50, %rd48;
	cvt.u32.u64 	%r30, %rd51;
	shr.u64 	%rd52, %rd47, %r30;
	or.b64  	%rd53, %rd52, %rd49;
	selp.b64 	%rd54, %rd46, %rd53, %p8;
	mov.u64 	%rd55, -3958705157555305931;
	{
	.reg .u32 %r0, %r1, %r2, %r3, %alo, %ahi, %blo, %bhi;
	mov.b64 	{%alo,%ahi}, %rd54;
	mov.b64 	{%blo,%bhi}, %rd55;
	mul.lo.u32 	%r0, %alo, %blo;
	mul.hi.u32 	%r1, %alo, %blo;
	mad.lo.cc.u32 	%r1, %alo, %bhi, %r1;
	madc.hi.u32 	%r2, %alo, %bhi, 0;
	mad.lo.cc.u32 	%r1, %ahi, %blo, %r1;
	madc.hi.cc.u32 	%r2, %ahi, %blo, %r2;
	madc.hi.u32 	%r3, %ahi, %bhi, 0;
	mad.lo.cc.u32 	%r2, %ahi, %bhi, %r2;
	addc.u32 	%r3, %r3, 0;
	mov.b64 	%rd56, {%r0,%r1};
	mov.b64 	%rd57, {%r2,%r3};
	}
	setp.gt.s64 	%p9, %rd57, 0;
	{
	.reg .u32 %r0, %r1, %r2, %r3, %a0, %a1, %a2, %a3, %b0, %b1, %b2, %b3;
	mov.b64 	{%a0,%a1}, %rd56;
	mov.b64 	{%a2,%a3}, %rd57;
	mov.b64 	{%b0,%b1}, %rd56;
	mov.b64 	{%b2,%b3}, %rd57;
	add.cc.u32 	%r0, %a0, %b0;
	addc.cc.u32 	%r1, %a1, %b1;
	addc.cc.u32 	%r2, %a2, %b2;
	addc.u32 	%r3, %a3, %b3;
	mov.b64 	%rd58, {%r0,%r1};
	mov.b64 	%rd59, {%r2,%r3};
	}
	selp.b64 	%rd60, %rd59, %rd57, %p9;
	selp.u64 	%rd61, 1, 0, %p9;
	add.s64 	%rd62, %rd48, %rd61;
	cvt.u64.u32 	%rd63, %r28;
	shl.b64 	%rd64, %rd63, 32;
	shl.b64 	%rd65, %rd62, 52;
	mov.u64 	%rd66, 4602678819172646912;
	sub.s64 	%rd67, %rd66, %rd65;
	add.s64 	%rd68, %rd60, 1;
	shr.u64 	%rd69, %rd68, 10;
	add.s64 	%rd70, %rd69, 1;
	shr.u64 	%rd71, %rd70, 1;
	add.s64 	%rd72, %rd67, %rd71;
	or.b64  	%rd73, %rd72, %rd64;
	mov.b64 	%fd4, %rd73;

$L__BB1_7:
	st.param.f64 	[func_retval0+0], %fd4;
	ret;

}

